#%RAML 1.0 NamedExample
warehousePOSTexample:
  {
            "country":"India",
            "location":"Ghaziabad",
            "state":"U.P.",
            "sub_location":"Raj Nagar",
            "mgr_id":"3"
          }