#%RAML 1.0 NamedExample
warehouseGETexample:
  {
                "wh_id":"1",
                "country":"India",
                "location":"Bareilly",
                "state":"U.P.",
                "sub_location":"Rajendra Nagar",
                "mgr_id":"2"
              }